apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
  name: kubernetes

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes
  labels:
    app: kubernetes
    service: kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes
      service: kubernetes
  template:
    metadata:
      labels:
        app: kubernetes
        service: kubernetes
    spec:
      serviceAccountName: kubernetes
      
      containers:
      - name: kubernetes-container
        image: hhana982/kubernetes:1.<version>
        ports:
        - containerPort: 5000
        
        env: 