apiVersion: v1
kind: Service
metadata:
  name: kubernetes
  labels:
    app: kubernetes
    service: kubernetes
spec:
  selector:
    app: kubernetes
    service: kubernetes
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP