apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
  name: kubernetes-db

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-db
  labels:
    app: kubernetes-db
    service: kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-db
      service: kubernetes
  template:
    metadata:
      labels:
        app: kubernetes-db
        service: kubernetes
    spec:
      serviceAccountName: kubernetes-db
      volumes:
      - name: kubernetes-db-volume
        persistentVolumeClaim:
          claimName: kubernetes-db
      containers:
      - name: kubernetes-db-container
        image: mysql
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: kubernetes-db-volume
        env: 
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpassword"