apiVersion: v1
kind: Service
metadata:
  name: kubernetes-db
  labels:
    app: kubernetes-db
    service: kubernetes
spec:
  selector:
    app: kubernetes-db
    service: kubernetes
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP